fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    body_listener:
        decoders:
            json: fos_rest.decoder.json
            xml: fos_rest.decoder.xml
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, xml ] }
            - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
    exception:
        enabled: true
