parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\EventListener\UrlCreationListener:
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\EventListener\UserCreationListener:
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\EventListener\KernelErrorListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
